### ISSUE TITLE
modifiers should be a property of the component

### ISSUE THREAD

**Issue by alanbsmith** [Decisiv/styled-components-modifiers#12]
## EXPECTED BEHAVIOR
Sometimes you just want to ask a component about its modifiers, but you can't. 😢 

## ACTUAL BEHAVIOR
```
Component.modifiers
#=> undefined
```

## SUGGESTED SOLUTION
Not sure yet. going to mess with it.

**Comment by tinynumbers** [comment]
I'm thinking that we can make this something that isn't actually exposed in the API or docs of SCM or `decisiv-ui-utils`, but provide an internal capability that is used by `buildStyledComponent` to sort of _inherit_ the modifiers.  I'll give it some thinkin'...

**Comment by andrewtpoe** [comment]
This functionality is not a part of what `styled-components-modifiers` provides, and is best handled in something like a factory function you use to build your styled component. 

I'm going to close this issue as `wontfix`.
